#!/bin/sh

# Restore /usr/lib with original libraries

#echo "Restore old libs and cleanup..."
#cp -f /root/.backup/libgcrypt.so.11.1.1 /usr/lib/
#cp -f /root/.backup/libgpg-error.so.0.4.0 /usr/lib/

# Copying was ok, remove backup dir
#[ -f /usr/lib/libgcrypt.so.11.1.1 ] && rm -rf /root/.backup

echo "Calling ldconfig..."
ldconfig
